#!/bin/sh
# Copyright 2019 Jérôme Poulin <jeromepoulin@gmail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. /etc/dockrouter/functions.sh

check_config /etc/wg-mpls.conf wg-mpls || exit 0
logger "Starting wireguard wg-mpls"
sv o wg-mpls
exec /usr/bin/wg setconf wg-mpls "$CONFDIR/`find_config_name wg-mpls`"
